{% set name = "pymem" %}
{% set version = "1.14.0" %}

{% set python_min = "3.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: "{{ name|lower }}-{{ version }}.tar.gz"
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "29f6c32bcad0032888afabadf97d1e4c7757f88873de4d79f7f4c1df9b9e7ef1"

build:
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - __win
    - python >={{ python_min }}

test:
  imports:
    - pymem

about:
  home: "https://pymem.readthedocs.io/en/latest/"
  license_file: LICENSE
  license: MIT
  summary: A Python library for manipulating Windows process memory
  doc_url: "https://pymem.readthedocs.io/en/latest/"
  dev_url: "https://github.com/srounet/pymem"

extra:
  recipe-maintainers:
    - chenghlee
